[package]
name = "vm-device"
version = "0.1.0"
authors = ["Samuel Ortiz <sameo@linux.intel.com>"]
repository = "https://github.com/rust-vmm/vm-device"
license = "Apache-2.0"
edition = "2018"

[dependencies]
vmm-sys-util = { git = "https://github.com/rust-vmm/vmm-sys-util.git", branch = "master" }

[features]
default = ["legacy_irq", "generic_msi", "pci_msi", "pci_msix"]
legacy_irq = []
msi_irq = []
generic_msi = ["msi_irq"]
pci_msi = ["msi_irq"]
pci_msix = ["msi_irq"]
